name: Download multiple workflow artifacts
description: An action that downloads and extracts multiple uploaded artifacts
author: marcofaggian
branding:
  icon: download
  color: blue
inputs:
  github_token:
    description: GitHub token
    required: false
    default: ${{github.token}}
  workflow:
    description: Workflow name
    required: true
  repo:
    description: Repository name with owner (like actions/checkout)
    required: false
    default: ${{github.repository}}
  pr:
    description: Pull request number
    required: false
  commit:
    description: Commit hash
    required: false
  branch:
    description: Branch name
    required: false
  event:
    description: Event type
    required: false
  names:
    description: Artifact name (download all artifacts in not specified)
    required: true
  paths:
    description: Where to unpack the artifact
    required: true
    default: "./"
runs:
  using: node16
  main: dist/main.js
